magephp:
  log_dir: /var/www/html/mage-logs
  log_limit: 10
  environments:
    staging:
      ssh:
        port: 22
        flags: -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ./deployment/key
        timeout: 60
      user: root
      #      branch: master
      from: ./
      symlink: laravel
      host_path: /var/www/
      releases: 10
      exclude:
        - ./.vscode
        - ./.gitignore
        - ./node_modules
        - ./storage/app/*
        - ./storage/logs/*
        - ./storage/framework/cache/*
        - ./storage/framework/sessions/*
        - ./storage/framework/views/*
        - ./storage/debugbar
        - ./tests
        - ./.env
      hosts:
        - 146.190.238.131
      pre-deploy:
      #        - composer/install
      #        - composer/dump-autoload
      on-deploy:
        #        - fs/copy: { from: '/var/www/shared/.env', to: '.env' }
        - exec: { cmd: 'cp /var/www/shared/.env .env', desc: 'Copy env file' }
        - exec: { cmd: 'touch new_file_from_deployment', desc: 'Create new file for testing purposes' }
        - exec: { cmd: 'chmod -R 777 ./storage', desc: 'Set storage permissions' }
        - exec: { cmd: 'php8.1 artisan migrate --force', desc: 'Migrate database' }
        - exec: { cmd: 'php8.1 artisan db:seed --force', desc: 'Seed database' }
      on-release:
      post-release:
      post-deploy:
    production:
      ssh:
        port: 22
        flags: -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ./deployment/key
        timeout: 60
      user: root
#      branch: master
      from: ./
      symlink: laravel
      host_path: /var/www/
      releases: 10
      exclude:
        - ./.vscode
        - ./.gitignore
        - ./node_modules
        - ./storage/app/*
        - ./storage/logs/*
        - ./storage/framework/cache/*
        - ./storage/framework/sessions/*
        - ./storage/framework/views/*
        - ./storage/debugbar
        - ./tests
        - ./.env
      hosts:
        - 146.190.238.131
      pre-deploy:
        - exec: { cmd: 'composer install', desc: 'Copy env file' }
#        - composer/install
#        - composer/dump-autoload
      on-deploy:
#        - fs/copy: { from: '/var/www/shared/.env', to: '.env' }
        - exec: { cmd: 'cp /var/www/shared/.env .env', desc: 'Copy env file' }
        - exec: { cmd: 'touch new_file_from_deployment', desc: 'Create new file for testing purposes' }
        - exec: { cmd: 'chmod -R 777 ./storage', desc: 'Set storage permissions' }
        - exec: { cmd: 'php8.1 artisan migrate --force', desc: 'Migrate database' }
        - exec: { cmd: 'php8.1 artisan config:cache', desc: 'Migrate database' }
      on-release:
      post-release:
      post-deploy:
